name: 'Deploy Status'
description: 'GitHub Action to report deployment status'
author: 'godban'
inputs:
  token:
    description: 'GitHub token'
    required: true
  state:
    description: 'Status of deploy. Can be "queued", "pending", "in_progress", "error", "failure", or "success"'
    required: true
  description:
    description: 'A short description of the status. The maximum description length is 140 characters'
    required: false
  environment:
    description: 'Name for the target deployment environment. For example, "production", "release", or "qa"'
    default: 'live'
    required: false
  environment_url:
    description: 'Sets the URL for accessing your environment'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: upload
  color: blue
